### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by an0rak-dev** [an0rak-dev/vscode-gcp-cloudbuild#1]
# What it's the actual situation on vscode-gcp-cloud ?

The source code of the extension isn't fully tested. We have a point of failure here as we don't check for regression on future developments.

# Describe the solution you'd like

Add unit tests to the sources, and integration / end-to-end tests to the plugin to prevent guture regressions.

# Additional informations

The jest framework is already setted up, and the `extension.ts` has some tests in it. This might be used as an example.

**Comment by jkaluzka** [comment]
Hi @an0rak-dev, I might increase code coverage a little bit if you want :)

**Comment by an0rak-dev** [comment]
Hi @jkaluzka 

I'm clearly interested to add more quality on the project ! Please be my guest 🙏 😄 

an0rak

**Comment by an0rak-dev** [comment]
Thanks to @jkaluzka this issue is now done.
